---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: jenkinsagent
  name: jenkinsagent
  namespace: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: jenkinsagent
  template:
    metadata:
      labels:
        k8s-app: jenkinsagent
      namespace: devops
      name: jenkinsagent
    spec:
      hostAliases:
        - ip: "192.168.1.200"
          hostnames:
            - "gitlab.idevops.site"
        - ip: "192.168.1.200"
          hostnames:
            - "sonar.idevops.site"
        - ip: "192.168.1.200"
          hostnames:
            - "nexus.idevops.site"
      containers:
        - name: jenkinsagent
          #image: jenkins/inbound-agent
          image: custom-build-agent:v2
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local:8080
            - name: JENKINS_SECRET
              value: 084570525dd4c12755c196b9ee61ab222b82b399e89ccb055f92f2a45a940b91
            - name: JENKINS_AGENT_NAME
              value: build01
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/workspace
          volumeMounts:
            - name: jenkins-build-cache
              mountPath: /home/jenkins/jenkins-build-cache
      volumes:
        - name: jenkins-build-cache
          persistentVolumeClaim:
            claimName: jenkins-build-cache